### ISSUE TITLE
chrono_logger not working with ruby 2.3.0

### ISSUE THREAD

**Issue by u1tnk** [ma2gedev/chrono_logger#3]
日本語で良いでしょうか？

ruby 2.3.0で以下のエラーが発生しました。
確認すると ruby2.3.0では `Logger::LogDevice::LogDeviceMutex` が NameErrorとなるため動作しないようです。(ドキュメントではあるのですが… [class Logger::LogDevice::LogDeviceMutex (Ruby 2.3.0)](http://docs.ruby-lang.org/ja/2.3.0/class/Logger=3a=3aLogDevice=3a=3aLogDeviceMutex.html))

修正したいところですが、 `Logger::LogDevice::LogDeviceMutex`が無いのでどう修正して良いかわからないのでエラー報告だけさせて頂きます。

```
NameError: uninitialized constant ChronoLogger::TimeBasedLogDevice::LogDeviceMutex
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/chrono_logger-1.1.0/lib/chrono_logger.rb:58:in `initialize'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/chrono_logger-1.1.0/lib/chrono_logger.rb:22:in `new'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/chrono_logger-1.1.0/lib/chrono_logger.rb:22:in `initialize'
/var/www/spon-server/releases/20160420155507/config/environments/staging.rb:83:in `new'
/var/www/spon-server/releases/20160420155507/config/environments/staging.rb:83:in `block in <top (required)>'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/railtie.rb:210:in `instance_eval'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/railtie.rb:210:in `configure'
/var/www/spon-server/releases/20160420155507/config/environments/staging.rb:1:in `<top (required)>'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:597:in `each'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:597:in `block in <class:Engine>'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
/var/www/spon-server/releases/20160420155507/config/environment.rb:5:in `<top (required)>'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/www/spon-server/shared/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
```

**Comment by sonots** [comment]
http://docs.ruby-lang.org/ja is human generated sites, so it would be old.
http://docs.ruby-lang.org/en is machine generated sites, so it should be new.

**Comment by ma2gedev** [comment]
Thank you for reporting. I translated title into English.

**Comment by ma2gedev** [comment]
@u1tnk 
Just published v1.1.1 including #4 pull request.
Many thanks!

**Comment by u1tnk** [comment]
@ma2gedev 
Thanks for your quick response!
